name             'rubygems'
maintainer       'RubyGems.org Ops Team'
license          'MIT'
description      'RubyGems base recipes'
version          '0.0.43'

depends 'chef-vault'
depends 'datadog'
depends 'ohai'
depends 'rubygems-apt'
depends 'rubygems-chef'
depends 'rubygems-cloud-init'
depends 'rubygems-hostname'
depends 'rubygems-hosts'
depends 'rubygems-logging'
depends 'rubygems-motd'
depends 'rubygems-ntp'
depends 'rubygems-people'
depends 'rubygems-ruby'
depends 'rubygems-sensu'
depends 'rubygems-ssh'
depends 'rubygems-utility'

supports 'ubuntu'
