source 'https://rubygems.org'

gem 'berkshelf',    '~> 3.0'
gem 'chef',         '~> 11.14'
gem 'chef-vault',   '~> 2.2.4'
gem 'chefspec',     '~> 4.0'
gem 'foodcritic',   '~> 5.0'
gem 'kitchen-docker'
gem 'kitchen-vagrant'
gem 'knife-backup'
gem 'knife-cookbook-cleanup'
gem 'knife-ec2'
gem 'rubocop',      '~> 0.23'
gem 'test-kitchen', '~> 1.0'
