name 'rubygems-app'

version '0.0.44'

depends 'apt'
depends 'chef-vault'
depends 'git'
depends 'nginx'
depends 'nodejs'
depends 'postfix', '3.2.0'
depends 'rubygems'
depends 'rubygems-metrics'
depends 'rubygems-ruby'
depends 'runit'
depends 'unicorn'
depends 'user'
