name 'rubygems-app'

version '0.0.94'

depends 'apt'
depends 'chef-vault'
depends 'datadog'
depends 'git'
depends 'chef_nginx', '~> 3.0.0'
depends 'nodejs'
depends 'rubygems-base'
depends 'rubygems-people'
depends 'rubygems-ruby'
depends 'runit'
depends 'sudo'
depends 'unicorn'
depends 'user'
depends 'logrotate'
